export {default as authRouter} from './auth.js'
export {router as userRouter} from './user.routes.js'
export {router as schoolRouter} from './school.routes.js'
export {router as profileRouter} from './profile.routes.js'
export {router as leadsRouter} from './lead.routes.js'
export {router as sourcesRouter} from './source.routes.js'
export {router as statusesRouter} from './status.routes.js'
export {router as groupsRouter} from './group.routes.js'
export {router as studentsRouter} from './student.routes.js'
export {router as clientsRouter} from './client.routes.js'
export {router as lessonsRouter} from './lesson.routes.js'
export {router as schedulesRouter} from './schedule.routes.js'
export {router as attendancesRouter} from './attendance.routes.js'
export {router as stylesRouter} from './style.routes.js'

